# Generated by Django 3.1.7 on 2021-03-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BdmEpixch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exch', models.DecimalField(decimal_places=14, max_digits=30)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DofExch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exch', models.DecimalField(decimal_places=14, max_digits=30)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FixerExch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exch', models.DecimalField(decimal_places=14, max_digits=30)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
